create table ef_user(
  user_id bigint not null primary key,
  follower_num bigint,
  streams_num bigint,
  events_num bigint,
  first_name varchar(255),
  last_name varchar(255),
  stream_name varchar(255),
  password varchar(64),
  email varchar(64),
  img_url varchar(1024),
  bio varchar(2048),
  city varchar(256),
  postcode varchar(64),
  state varchar(64),
  website varchar(1024),
  facebook varchar(128),
  twitter varchar(128),
  instagram varchar(128),
--   facebook_friends
  fb_token varchar(1024),
  source_type varchar(128),
  is_featured boolean,
  created_at timestamp default current_timestamp,
  updated_at timestamp default current_timestamp
);
